repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
      - id: check-yaml
      - id: pretty-format-json
        args: ["--indent", "2", "--autofix", "--no-sort-keys"]
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
  - repo: local
    hooks:
      - id: terraform-fmt
        name: terraform fmt
        description: runs terraform fmt
        entry: terraform fmt -recursive
        language: system
        pass_filenames: false
