name: Function App Deployment
on:
  push:
    branches:
      - main
    paths:
      - "**.py"

  pull_request:
    branches:
      - main
    paths:
      - "**.py"

jobs:
  function_test:
    uses: ./.github/workflows/_functionAppTestTemplate.yml
    name: "Function App Test"
    with:
      python_version: "3.10"
      function_directory: "./code/function"

  function_deploy:
    uses: ./.github/workflows/_functionAppDeployTemplate.yml
    name: "Function App Deploy"
    needs: [function_test]
    # if: github.event_name == 'push' || github.event_name == 'release'
    with:
      environment: "dev"
      python_version: "3.10"
      function_directory: "./code/function"
      function_name: "myfunc-dev-fctn001"
    secrets:
      FUNCTION_PUBLISH_PROFILE: ${{ secrets.FUNCTION_PUBLISH_PROFILE }}
