name: Function App Deployment
on:
  push:
    branches:
      - main
    paths:
      - "**.py"
      - "code/function/**"

  pull_request:
    branches:
      - main
    paths:
      - "**.py"
      - "code/function/**"

jobs:
  function_test:
    uses: ./.github/workflows/_functionAppTestTemplate.yml
    name: "Function App Test"
    with:
      python_version: "3.10"
      function_directory: "./code/function"

  function_container:
    uses: ./.github/workflows/_containerTemplate.yml
    name: "Function App Container"
    needs: [function_test]
    with:
      environment: "dev"
      working_directory: "./code/function"
      registry_uri: "ghcr.io"
      image_namespace_name: "PerfectThymeTech"
      image_name: "AzureFunctionPython"
    secrets:
      USER_NAME: ${{ github.actor }}
      PASSWORD: ${{ secrets.GITHUB_TOKEN }}

  function_deploy:
    uses: ./.github/workflows/_functionAppDeployTemplate.yml
    name: "Function App Deploy"
    needs: [function_test]
    if: github.event_name == 'push' || github.event_name == 'release'
    with:
      environment: "dev"
      python_version: "3.10"
      function_directory: "./code/function"
      function_name: "myfunc-dev-fctn001"
    secrets:
      TENANT_ID: ${{ secrets.TENANT_ID }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
