name: Python - Test
on:
  push:
    branches:
      - main
    paths:
      - "code/function/**"
      - "tests/**"
      - "requirements.txt"
      - ".github/workflows/python.yml"
  pull_request:
    branches:
      - main
    paths:
      - "code/function/**"
      - "tests/**"
      - "requirements.txt"
      - ".github/workflows/python.yml"

jobs:
  lint:
    name: Python Test
    runs-on: ubuntu-latest

    steps:
      # Setup Python 3.10
      - name: Setup Python 3.10
        id: python_setup
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Checkout repository
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@v3

      # Run Python Tests
      - name: Run Python Tests
        id: python_test
        run: |
          pip install -r ./code/function/requirements.txt -q
          pip install -r requirements.txt -q
          python -m pytest
