name: Infrastructure Deployment
on:
  push:
    branches:
      - main
    paths:
      - "**.tf"
      - "code/infra/**"
      - "config/**"
      - ".github/workflows/terraform.yml"
      - ".github/workflows/_terraformEnvironmentTemplate.yml"

  pull_request:
    branches:
      - main
    paths:
      - "**.tf"
      - "code/infra/**"
      - "config/**"
      - ".github/workflows/terraform.yml"
      - ".github/workflows/_terraformEnvironmentTemplate.yml"

jobs:
  terraform_dev:
    uses: ./.github/workflows/_terraformEnvironmentTemplate.yml
    name: "Dev"
    with:
      environment: "dev"
      config: "PerfectThymeTech"
      terraform_version: "1.9.6"
      node_version: 20
      working_directory: "./code/infra"
      tenant_id: "37963dd4-f4e6-40f8-a7d6-24b97919e452"
      subscription_id: "1fdab118-1638-419a-8b12-06c9543714a0"
    secrets:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      MY_SAMPLE_SECRET: ${{ secrets.MY_SAMPLE_SECRET }}

  terraform_dev_destroy:
    uses: ./.github/workflows/_terraformDestroyTemplate.yml
    name: "Dev - Destroy"
    needs: [terraform_dev]
    with:
      environment: "dev"
      config: "PerfectThymeTech"
      terraform_version: "1.9.6"
      node_version: 20
      working_directory: "./code/infra"
      tenant_id: "37963dd4-f4e6-40f8-a7d6-24b97919e452"
      subscription_id: "1fdab118-1638-419a-8b12-06c9543714a0"
    secrets:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      MY_SAMPLE_SECRET: ${{ secrets.MY_SAMPLE_SECRET }}
